export const UPDATE_EDITOR_STATE = 'UPDATE_EDITOR_STATE';

export const CODE_MESSAGE_RECEIVED = 'CODE_MESSAGE_RECEIVED';
export const CHAT_MESSAGE_RECEIVED = 'CHAT_MESSAGE_RECEIVED';
export const CONTROLL_MESSAGE_RECEIVED = 'CONTROLL_MESSAGE_RECEIVED';
export const ERROR_MESSAGE_RECEIVED = 'ERROR_MESSAGE_RECEIVED';
export const JHS_MESSAGE_RECEIVED = 'JHS_MESSAGE_RECEIVED';

export const SOCKET_STATUS_CHANGED = 'SOCKET_STATUS_CHANGED';
export const SOCKET_ERROR_OCCURED = 'SOCKET_ERROR_OCCURED';
export const HIDE_ERROR_INFO = 'HIDE_ERROR_INFO';